export default {
    PRODUCT_LIST: "/product/viewproduct",
    PRODUCT_DELETE:"/product/delete",
    CATEGORY_LIST: "/category/category-list",
    CATEGORY_ADD: "/category/add",
    CATEGORY_DELETE: "/category/delete",
    CUSTOMER_COUNT: "/admin/customer/count",
    SELLER_COUNT: "/admin/seller/count",
    ORDER_COUNT: "/admin/order/count",
    CATEGORY_UPDATE: "/category",
    CUSTOMERS_ORDER: "/order/orderdetail",
    CUSTOMERS_ORDER_ITEM: "/order/orderitem",
    ADMIN_SIGNIN: "/admin/google-signin",
    ADMIN_SIGNIN1:"/admin/signin",
    ORDER_STATUS: "/order/updateorderstatus/",
    ORDER_BY_SELLER: "/order/getorderbyseller/",
    SELLER_STATUS:"/admin/",
    SELLER_STATUS1:"/admin/seller/",
    SELLER_PRODUCT:"/product/productlist/",
    PRODUCT_DELETE:"/product/delete/",
    PRODUCT_UPDATE:"/product/update/",
    SELLER_VIEW_CUSTOMER:"/admin/sellerviewcustomer/"
}